version: '3'
services:
  selfsigned:
    build:
        context: .
        dockerfile: certs.Dockerfile
    container_name: gencerts
    volumes:
        - ./certs:/certs
    env_file:
        - secrets
  
  mariadb: 
    image: "mariadb/server:10.3"
    container_name: seb-server-mariadb
    volumes:
        - .:/etc/mysql/conf.d
        - ./certs:/etc/mysql/certs
        - seb-server-mariadb-data:/var/lib/mysql
    env_file:
        - secrets
    ports:
        - 3306:3306
    networks:
        - seb-server-network
    depends_on:
      - "selfsigned"

  seb-server:
      build:
          context: .
          dockerfile: sebserver.Dockerfile
          args:
              - GIT_TAG=
              - SEBSERVER_VERSION=0.4.1-beta-SNAPSHOT
      container_name: seb-server
      env_file:
        - secrets
      environment:
        - ADDITIONAL_DNS=dns:127.0.0.1,dns:seb-server
      volumes:
        - ./application-prod.properties:/sebserver/application-prod.properties
        - ./certs:/certs
        - ./secrets:/sebserver/secrets
      ports:
          - 443:443
          - 8080:80
      logging:
        driver: "json-file"
        options:
            max-size: "200k"
            max-file: "10"
      networks:
          - seb-server-network
      depends_on:
          - "mariadb"
            
networks:
  seb-server-network:

volumes:
  seb-server-mariadb-data: