version: '3'
services:
  mariadb: 
    image: "mariadb/server:10.3"
    container_name: seb-server-mariadb
    environment:
        MYSQL_ROOT_PASSWORD: somePW
    ports:
        - 3306:3306
    networks:
        - ralph

  seb-server:
      build:
          context: .
          args:
              - GIT_TAG=
              - SEBSERVER_VERSION=0.4.0-SNAPSHOT
      container_name: seb-server
      environment:
          - SERVER_ADDRESS=0.0.0.0
          - SERVER_PORT=8080
          - DBSERVER_ADDRESS=seb-server-mariadb
          - DBSERVER_PORT=3306
          - DBSERVER_PWD=somePW
          - GUICLIENT_PWD=somePW
          - INTERNAL_PWD=somePW
      ports:
          - 8080:8080
      networks:
          - ralph
      depends_on:
          - "mariadb"
            
networks:
  ralph: